### PR TITLE
ci: added github-actions

### PR DESCRIPTION
**Pull request by ansrivas**
Integrated a basic github workflow to run all the tests. 

( Will also integrate the docs in another next PR )

You can see this running here on my fork - https://github.com/ansrivas/paperclip/pull/1

### CODE REVIEW

**Comment by ansrivas** [comment]
@tiagolobocastro If you will have some time, have a look at this one. IMO it would help to unblock the PRs

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
this is great, thanks @ansrivas ! However, looks like github is still waiting on the travis-ci... maybe we need to delete the 
.travis.yml ?

**Comment by ansrivas** [comment]
Hmm, this is weird, I removed the `.travis.yml` file and added another dummy commit.  It still is waiting for the status.
Probably we can make it work like this:
- first PR remove the .travis file ( you can merge that )
- second PR I rebase and open one with github actions

**Comment by tiagolobocastro** [comment]
I won't be able to merge if the checks don't complete, I'm only a collaborator so I don't have the necessary permissions.
@wafflespeanut we might need your help with this

**Comment by tiagolobocastro** [comment]
@ansrivas I've removed the travis requirement, do you mind pushing again to see if actions will run now?

**Comment by tiagolobocastro** [comment]
I don't get it.. still not running... I don't have time now to investigate more, I'll try to do so tonight

**Comment by ansrivas** [comment]
> I don't get it.. still not running... I don't have time now to investigate more, I'll try to do so tonight

The same for me, I tried it on my fork, it just works fine. I will also look into it later today.

**Comment by tiagolobocastro** [comment]
@ansrivas I've removed the travis file from the main branch, could you please open a new PR with just the GHA file change?

**Pull request closed without merging**
