### PR TITLE
fix: Append scope services instead of replacing

### LINKED ISSUE #380: [Actix] If both a GET and POST is defined on the same path,  only one gets included
Noticed this issue today while checking the spec manually. I've got the following routes:
```rs
.route("[..]/wifi", web::get().to(endpoints::v1::[..]::get))
.route("[..]/wifi", web::post().to(endpoints::v1::[..]::set))
```
Where `[..]` indicates a path that has been left out. Only the `POST` endpoint is in the spec, the `GET` is not.

## Versions
- Actix: `3.3.3`
- Paperclip: Local fork (see #373), essentially v0.6.1
- Rust: `1.58`

### PR DESCRIPTION
**Pull request by fritterhoff**
So instead of inserting an item and overwriting the existing I simply append the existing maps.

Should fix #380

### CODE REVIEW

**Review by TobiasDeBruijn — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
Thanks @fritterhoff! Could you please fix the " Lint / rustfmt (stable) (pull_request) Failing after 8s — rustfmt (stable) " ?

**Comment by fritterhoff** [comment]
@tiagolobocastro done.

**Comment by fritterhoff** [comment]
I will check the failing tests in a minute.

**Comment by fritterhoff** [comment]
Actually I have no idea why that changed but I think that is not affected by my changes...?

**Comment by tiagolobocastro** [comment]
> Actually I have no idea why that changed but I think that is not affected by my changes...?

The stable build and test should pass; the nightly has been failing for some time now so I think we can safely ignore it.

**Comment by fritterhoff** [comment]
> > Actually I have no idea why that changed but I think that is not affected by my changes...?
> 
> The stable build and test should pass; the nightly has been failing for some time now so I think we can safely ignore it.

Yeah. I added a missing `/`. I thought was working some days ago 😕

**Comment by fritterhoff** [comment]
So from my point of view we could merge this. I have no further ideas why the nightly builds fail.

**Comment by tiagolobocastro** [comment]
Thanks @fritterhoff !

**Pull request merged**
