### PR TITLE
Update paperclip version

### PR DESCRIPTION
**Pull request by JackBocresion**
Paperclip version 0.4 is not compatible with Actix 3, only version 0.5 works

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]
Thanks @JackBocresion, could you please also remove the `**experimental**` from the doc ( at the beginning), that not longer applies.

**Comment by JackBocresion** [comment]
Done!

**Comment by tiagolobocastro** [comment]
For some reason the build doesn't seem to be running...

**Comment by JackBocresion** [comment]
That's strange. I replaced nightly for stable and everything seems to be working fine with no errors.

**Comment by tiagolobocastro** [comment]
Seems something wrong with travis-ci. Maybe try pushing with a different commit id to see if that kicks it into life or something?

**Comment by tiagolobocastro** [comment]
@wafflespeanut travis does not seem to be running, would you happen to know why? I tried checking it out at travis-ci.com but it's telling me I'm not the repository owner.

**Pull request merged**
