### PR TITLE
feat: support PATCH methods

### PR DESCRIPTION
**Pull request by kenkoooo**
Hi, I would like to support PATCH methods as other methods. Could you take a look into it? If there's something I missed, please let me know. Thanks!

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
thanks @kenkoooo, would you mind also updating the [changelog ](https://github.com/paperclip-rs/paperclip/blob/master/CHANGELOG.md)?

**Comment by kenkoooo** [comment]
Thank you for reviewing! I updated CHANGELOG.

**Comment by tiagolobocastro** [comment]
Sorry @kenkoooo I was unavailable during the week and just merged another PR so would you mind resolving the conflicts?

**Comment by kenkoooo** [comment]
@tiagolobocastro No worries! I resolved the conflicts.

**Comment by tiagolobocastro** [comment]
Hey @kenkoooo the stable lint seem to be failing, could you please take a look at it? Seems to be "cancelled", not sure what that means :/

**Comment by kenkoooo** [comment]
image
According to its summary, the job was canceled because "nightly" failed. 
https://github.com/paperclip-rs/paperclip/actions/runs/2280158035

**Comment by kenkoooo** [comment]
I pushed https://github.com/paperclip-rs/paperclip/pull/422/commits/5a97fdef42ce49440dc7a4916808ae8501c56985 to avoid canceling the stable linter even if the nightly linter failed.

We can fix the code to pass the nightly linter, but I guess we don't want to apply the nightly rules.

**Comment by tiagolobocastro** [comment]
Hi @kenkoooo seems with your changes the clippy and fmt are not even running anymore for some reason.

**Comment by kenkoooo** [comment]
Cool. So I reverted my latest change on lint.yml.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by kenkoooo** [comment]
@tiagolobocastro Would you mind publishing the latest version to crates.io? Thanks!

**Pull request merged**
