### PR TITLE
ci: added github-actions

### PR DESCRIPTION
**Pull request by ansrivas**

### CODE REVIEW

**Comment by ansrivas** [comment]
@tiagolobocastro this seems to be working. You will need to approve this workflow.

**Comment by tiagolobocastro** [comment]
Cool it's running! Would you be able to add the missing bits which we had on travis, the docs and the check? Then there's the docs from `paperclip.waffles.space`, not sure how that works though.
Anyway if you don't have time for that I can try to add it later, it's a good start to get the CI back :)

**Comment by ansrivas** [comment]
> Cool it's running! Would you be able to add the missing bits which we had on travis, the docs and the check? Then there's the docs from `paperclip.waffles.space`, not sure how that works though. Anyway if you don't have time for that I can try to add it later, it's a good start to get the CI back :)

Thanks for your efforts. And sure, I have a semi-working branch with clippy/rustfmt parts and then the docs will follow.

**Comment by ansrivas** [comment]
Added it here with clippy/rustfmt - https://github.com/paperclip-rs/paperclip/pull/340

**Review by tiagolobocastro — APPROVED** [review]

**Pull request merged**
