### PR TITLE
Rapidoc fixes

### PR DESCRIPTION
**Pull request by snaggen**
Rapidoc didn't compile since it needs "include_dir"
I also added an extra route to avoid having to specify index.html + a check to remove any trailing / in the specified rapidoc path

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Hey @snaggen, looks good thanks! could you please fix the gha lint failures?

**Comment by snaggen** [comment]
Sorry for me being sloppy and missing to compile with feature actix3. It should compile now.

**Comment by tiagolobocastro** [comment]
> Sorry for me being sloppy and missing to compile with feature actix3. It should compile now.

No worries at all! Btw looks like it's still failing the linter though

**Comment by snaggen** [comment]
The nightly clippy seems to fail on models.rs, and some Eq issue. Nothing that seems related to these changes. Are you sure that is not from master?

**Comment by snaggen** [comment]
And the other clippy seems to have been cancelled.

**Comment by snaggen** [comment]
I have had a closer look at the clippy warnings, and I get the same clippy warnings in master, so the clippys are not related to this PR. However, while doing this I found a related unused HttpRequest warning (that still is in master, but not visible due to not compiling without this PR) when you sepecify rapidoc, without swagger-ui. So I fixed that now when I was at it.

**Comment by snaggen** [comment]
I have fixed the clippy warnings as a separate PR since it was not related to this  #432

**Review by tiagolobocastro — APPROVED** [review]

**Pull request merged**
