### PR TITLE
doc: Add instructions for git submodules

### PR DESCRIPTION
**Pull request by RaulTrombin**
Solves:
https://github.com/paperclip-rs/paperclip/issues/534

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
What about the previous suggestion of adding the git command to the make prepare command? Do you think it's better to keep as is?

**Comment by RaulTrombin** [comment]
> What about the previous suggestion of adding the git command to the make prepare command? Do you think it's better to keep as is?

This would also resolve the issue. I tested it on a clean clone of the repo, and it seems fine. May I go ahead and add this commit as well?

**Comment by tiagolobocastro** [comment]
> > What about the previous suggestion of adding the git command to the make prepare command? Do you think it's better to keep as is?
> 
> This would also resolve the issue. I tested it on a clean clone of the repo, and it seems fine. May I go ahead and add this commit as well?

Yeah I think so if you don't mind

**Comment by RaulTrombin** [comment]
> > > What about the previous suggestion of adding the git command to the make prepare command? Do you think it's better to keep as is?
> > 
> > 
> > This would also resolve the issue. I tested it on a clean clone of the repo, and it seems fine. May I go ahead and add this commit as well?
> 
> Yeah I think so if you don't mind

did it, 
removed the unnecessary aditional  command if user skips submodule, as the 'make prepare' will fix it.

**Pull request merged**
